name: Post to X

on:
  repository_dispatch:
    types: [run-post]

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Chrome & Python
        uses: browser-actions/setup-chrome@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install selenium slack_sdk webdriver-manager requests

      - name: Run Selenium Post
        run: python post_to_x.py
        env:
          DATE: ${{ github.event.client_payload.date }}
          TIME: ${{ github.event.client_payload.time }}
          TEXT: ${{ github.event.client_payload.text }}
          IMAGE: ${{ github.event.client_payload.image }}
          SLACK_WEBHOOK_URL: ${{ github.event.client_payload.slack }}
          DRIVE_FOLDER_ID: ${{ github.event.client_payload.drive_folder_id }}
          X_ID: ${{ secrets.X_ID }}
          X_PASS: ${{ secrets.X_PASS }}