name: Post to X

on:
  repository_dispatch:
    types: [run-post]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Chrome & Python
        uses: browser-actions/setup-chrome@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install selenium slack_sdk webdriver-manager requests

      - name: Run Selenium Post
        env:
          TEXT: ${{ github.event.client_payload.text }}
          IMAGE: ${{ github.event.client_payload.image }}
          SLACK_WEBHOOK_URL: ${{ github.event.client_payload.slack }}
          DRIVE_FOLDER_ID: ${{ github.event.client_payload.drive_folder_id }}
          X_EMAIL: ${{ github.event.client_payload.X_EMAIL }}
          X_USERNAME: ${{ github.event.client_payload.X_USERNAME }}
          X_PASSWORD: ${{ github.event.client_payload.X_PASSWORD }}
        run: python post_to_x.py